
const express=require("express"),cors=require("cors"),helmet=require("helmet"),bcrypt=require("bcryptjs"),jwt=require("jsonwebtoken"),axios=require("axios"),cheerio=require("cheerio"),rateLimit=require("express-rate-limit");
const {PrismaClient}=require("@prisma/client"); const OpenAI=require("openai"); const prisma=new PrismaClient(); const app=express();
const PORT=process.env.PORT||5000, JWT_SECRET=process.env.JWT_SECRET||"change_me", OWNER_EMAIL=(process.env.OWNER_EMAIL||"simonedepadova0088@gmail.com").toLowerCase();
app.use(helmet({crossOriginResourcePolicy:false})); app.use(cors({origin:true,credentials:true})); app.use(express.json({limit:"3mb"})); app.use(rateLimit({windowMs:60000,max:240}));
function tok(u){return jwt.sign({userId:u.id,role:u.role},JWT_SECRET,{expiresIn:"7d"})}
function auth(req,res,next){let h=req.headers.authorization||"",t=h.startsWith("Bearer ")?h.slice(7):null;if(!t)return res.status(401).json({error:"Unauthorized"});try{req.user=jwt.verify(t,JWT_SECRET);next()}catch(e){res.status(401).json({error:"Invalid token"})}}
const s=v=>typeof v==="string"?v.trim():"";
function contactQuality(l){let q=0;if(l.phone)q+=20;if(l.email)q+=30;if(l.instagram)q+=15;if(l.facebook)q+=10;if(l.linkedin)q+=10;if(l.whatsapp)q+=15;return Math.min(100,q)}
function score(l){let n=20,b=[]; if(!l.website){n+=28;b.push("Nessun sito web: grande opportunità.")} else {n-=8;b.push("Sito presente: opportunità audit/upgrade.")} if((l.rating||0)>=4.3){n+=15;b.push("Rating alto.")} if((l.reviews||0)>=50){n+=18;b.push("Molte recensioni.")} if(l.phone){n+=8;b.push("Telefono disponibile.")} if(l.email||l.instagram||l.facebook||l.linkedin||l.whatsapp){n+=12;b.push("Contatti digitali trovati.")} if((l.reviews||0)<5){n-=10;b.push("Poche recensioni.")} n=Math.max(0,Math.min(100,Math.round(n))); return {aiScore:n,opportunityLevel:n>=85?"very hot":n>=70?"hot":n>=45?"warm":"cold",scoreExplanation:b.join(" ")}}
async function googlePlaces(niche,city,limit=20){if(!process.env.GOOGLE_API_KEY)return[{businessName:`Demo ${niche} ${city}`,address:city,rating:4.5,reviews:120,website:"",mapsUrl:"https://maps.google.com",niche,city,placeId:"demo"}]; let {data}=await axios.post("https://places.googleapis.com/v1/places:searchText",{textQuery:`${niche} ${city}`,maxResultCount:Math.min(+limit||20,20)},{headers:{"Content-Type":"application/json","X-Goog-Api-Key":process.env.GOOGLE_API_KEY,"X-Goog-FieldMask":"places.id,places.displayName,places.formattedAddress,places.rating,places.userRatingCount,places.googleMapsUri,places.websiteUri,places.nationalPhoneNumber"},timeout:20000}); return (data.places||[]).map(p=>({businessName:p.displayName?.text||"Business",phone:p.nationalPhoneNumber||"",address:p.formattedAddress||"",rating:p.rating||null,reviews:p.userRatingCount||0,website:p.websiteUri||"",mapsUrl:p.googleMapsUri||"",niche,city,placeId:p.id||""}))}
function extract(html){let $=cheerio.load(html),txt=$.html(),emails=txt.match(/[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-z]{2,}/g),links=[];$("a[href]").each((_,e)=>links.push(String($(e).attr("href")||"")));let f=n=>links.find(l=>l.toLowerCase().includes(n))||"";return{email:emails?[...new Set(emails)][0]:"",instagram:f("instagram.com"),facebook:f("facebook.com"),linkedin:f("linkedin.com"),tiktok:f("tiktok.com"),youtube:f("youtube.com"),whatsapp:links.find(l=>l.toLowerCase().includes("wa.me")||l.toLowerCase().includes("whatsapp"))||""}}
async function enrich(l){if(!l.website)return {...l,contactQuality:contactQuality(l)};try{let {data}=await axios.get(l.website,{timeout:12000,maxRedirects:4,headers:{"User-Agent":"LeadFinderAI/3.0"}}),found=extract(String(data)),m={...l};Object.entries(found).forEach(([k,v])=>{if(v)m[k]=v});m.contactQuality=contactQuality(m);m.enrichmentVerified=!!(m.email||m.instagram||m.facebook||m.linkedin||m.whatsapp);return m}catch(e){return {...l,contactQuality:contactQuality(l)}}}
async function outreach(l,opt={}){let fallback={subject:`Opportunità digitale per ${l.businessName}`,short:`Ciao ${l.businessName}, ho notato un'opportunità per aumentare richieste e fiducia online con un sito moderno.`,professional:`Buongiorno, analizzando la vostra presenza online credo ci sia spazio per aumentare contatti e conversioni con una presenza digitale più forte. Posso mostrarvi 2 idee pratiche?`,aggressive:`Probabilmente state perdendo clienti perché la vostra presenza digitale non converte abbastanza. Posso aiutarvi a trasformarla in un canale di acquisizione.`,whatsapp:`Ciao! Ho visto ${l.businessName}: posso mandarvi 2 idee per portarvi più clienti online?`,instagram:`Ciao! Complimenti per l'attività 🙌 Ho notato un'opportunità digitale interessante per ${l.businessName}.`,cta:"Vuoi un esempio gratuito?"}; if(!process.env.OPENAI_API_KEY)return fallback;try{let openai=new OpenAI({apiKey:process.env.OPENAI_API_KEY}),prompt=`Genera JSON outreach in ${opt.lang||"it"} tono ${opt.tone||"professionale"} per ${JSON.stringify(l)} con subject,short,professional,aggressive,whatsapp,instagram,cta`;let c=await openai.chat.completions.create({model:"gpt-4o-mini",response_format:{type:"json_object"},messages:[{role:"system",content:"Esperto sales copywriting per agenzie web."},{role:"user",content:prompt}]});return JSON.parse(c.choices[0].message.content)}catch(e){return fallback}}
app.get("/health",(_,res)=>res.json({status:"online",version:"enterprise-3.0"}));
app.post("/api/auth/register",async(req,res)=>{try{let email=s(req.body.email).toLowerCase(),password=s(req.body.password),fullName=s(req.body.fullName);if(!email.includes("@")||password.length<8)return res.status(400).json({error:"Registrazione non valida"});if(await prisma.user.findUnique({where:{email}}))return res.status(409).json({error:"Email già registrata"});let user=await prisma.user.create({data:{email,password:await bcrypt.hash(password,12),fullName,role:email===OWNER_EMAIL?"OWNER":"USER",referralCode:Math.random().toString(36).slice(2,9).toUpperCase()}});res.json({token:tok(user),user:{id:user.id,email:user.email,fullName:user.fullName,role:user.role,plan:user.plan}})}catch(e){console.error(e);res.status(500).json({error:"Registrazione fallita"})}});
app.post("/api/auth/login",async(req,res)=>{let email=s(req.body.email).toLowerCase(),password=s(req.body.password),u=await prisma.user.findUnique({where:{email}});if(!u||!(await bcrypt.compare(password,u.password)))return res.status(401).json({error:"Login non valido"});res.json({token:tok(u),user:{id:u.id,email:u.email,fullName:u.fullName,role:u.role,plan:u.plan}})});
app.post("/api/leads/search",auth,async(req,res)=>{try{let niche=s(req.body.niche||req.body.category),city=s(req.body.city);if(!niche||!city)return res.status(400).json({error:"Inserisci tipo di impresa e città"});let search=await prisma.search.create({data:{userId:req.user.userId,name:`${niche} ${city}`,niche,city}}),places=(await googlePlaces(niche,city,req.body.limit)).sort((a,b)=>(a.website?1:0)-(b.website?1:0)),out=[];for(let p of places){let d=req.body.enrich?await enrich(p):p,sc=score(d);let lead=await prisma.lead.create({data:{userId:req.user.userId,searchId:search.id,...d,...sc,contactQuality:contactQuality(d)}});out.push(lead)}await prisma.user.update({where:{id:req.user.userId},data:{searchesCount:{increment:1}}});res.json({search,leads:out})}catch(e){console.error(e.response?.data||e);res.status(500).json({error:"Ricerca fallita. Controlla GOOGLE_API_KEY e Places API."})}});
app.get("/api/leads",auth,async(req,res)=>res.json(await prisma.lead.findMany({where:{userId:req.user.userId},orderBy:{createdAt:"desc"},take:500})));
app.post("/api/leads/:id/enrich",auth,async(req,res)=>{let l=await prisma.lead.findFirst({where:{id:req.params.id,userId:req.user.userId}});if(!l)return res.status(404).json({error:"Lead non trovato"});let e=await enrich(l),sc=score(e),u=await prisma.lead.update({where:{id:l.id},data:{...e,...sc,contactQuality:contactQuality(e)}});res.json(u)});
app.post("/api/ai/outreach",auth,async(req,res)=>{let l=req.body.leadId?await prisma.lead.findFirst({where:{id:req.body.leadId,userId:req.user.userId}}):req.body.lead;if(!l)return res.status(404).json({error:"Lead non trovato"});let m=await outreach(l,req.body.options||{});if(req.body.leadId)await prisma.outreachLog.create({data:{userId:req.user.userId,leadId:l.id,channel:"ai",message:JSON.stringify(m)}});res.json(m)});
app.post("/api/ai/score",auth,async(req,res)=>{let l=req.body.leadId?await prisma.lead.findFirst({where:{id:req.body.leadId,userId:req.user.userId}}):req.body.lead;if(!l)return res.status(404).json({error:"Lead non trovato"});let sc=score(l);res.json({...sc,breakdown:[{label:"Digitalizzazione",value:l.website?55:15},{label:"Urgenza",value:l.website?45:88},{label:"Potenziale",value:Math.min(100,40+(l.reviews||0)/2)},{label:"Contattabilità",value:contactQuality(l)}]})});
app.post("/api/audit/website",auth,async(req,res)=>{let l=req.body.leadId?await prisma.lead.findFirst({where:{id:req.body.leadId,userId:req.user.userId}}):req.body.lead;if(!l)return res.status(404).json({error:"Lead non trovato"});let a=!l.website?{score:15,summary:"Sito non presente: forte opportunità.",issues:["Nessun sito trovato"],opportunities:["Nuovo sito","SEO locale","CTA"]}:{score:65,summary:"Audit base: verificare performance, mobile, SEO e CTA.",issues:["Performance da verificare","SEO locale","CTA"],opportunities:["Conversioni","Branding","Lead inbound"]}; if(req.body.leadId)await prisma.lead.update({where:{id:l.id},data:{auditScore:a.score,auditSummary:a.summary}});res.json(a)});
app.post("/api/whatsapp/open",auth,(req,res)=>{let phone=String(req.body.phone||"").replace(/[^\d+]/g,"");if(!phone)return res.status(400).json({error:"Numero mancante"});res.json({url:`https://wa.me/${phone.replace("+","")}?text=${encodeURIComponent(req.body.message||"")}`})});
app.get("/api/searches",auth,async(req,res)=>res.json(await prisma.search.findMany({where:{userId:req.user.userId},include:{leads:true},orderBy:{createdAt:"desc"}})));
app.patch("/api/searches/:id",auth,async(req,res)=>{await prisma.search.updateMany({where:{id:req.params.id,userId:req.user.userId},data:{name:s(req.body.name)}});res.json({ok:true})});
app.get("/api/crm",auth,async(req,res)=>{let leads=await prisma.lead.findMany({where:{userId:req.user.userId},orderBy:{updatedAt:"desc"}});res.json(["new","contacted","interested","meeting","closed"].map(status=>({status,leads:leads.filter(l=>l.crmStatus===status)})))});
app.patch("/api/crm/leads/:id",auth,async(req,res)=>{await prisma.lead.updateMany({where:{id:req.params.id,userId:req.user.userId},data:{crmStatus:req.body.status||"contacted",tags:req.body.tags||""}});res.json({ok:true})});
app.post("/api/automations",auth,async(req,res)=>{let {name,niche,city,frequency}=req.body;if(!name||!niche||!city)return res.status(400).json({error:"Automazione non valida"});res.json(await prisma.automation.create({data:{userId:req.user.userId,name,niche,city,frequency:frequency||"daily"}}))});
app.get("/api/automations",auth,async(req,res)=>res.json(await prisma.automation.findMany({where:{userId:req.user.userId},orderBy:{createdAt:"desc"}})));
app.get("/api/billing/plans",auth,(req,res)=>res.json({plans:[{id:"FREE",price:0},{id:"PRO",price:49},{id:"AGENCY",price:149}]}));
app.get("/api/referral",auth,async(req,res)=>{let u=await prisma.user.findUnique({where:{id:req.user.userId}}),code=u.referralCode||Math.random().toString(36).slice(2,9).toUpperCase();if(!u.referralCode)await prisma.user.update({where:{id:u.id},data:{referralCode:code}});let referred=await prisma.user.count({where:{referredBy:code}});res.json({code,link:`https://leadfinder.ai/invite/${code}`,referred,achievements:[{name:"Hai trovato 100 lead",unlocked:u.searchesCount>=5},{name:"Top scanner",unlocked:u.searchesCount>=20},{name:"Growth hacker badge",unlocked:referred>=3}]})});
app.get("/api/owner/users",auth,async(req,res)=>{let me=await prisma.user.findUnique({where:{id:req.user.userId}});if(me.role!=="OWNER")return res.status(403).json({error:"Owner only"});res.json(await prisma.user.findMany({select:{id:true,email:true,fullName:true,role:true,plan:true,searchesCount:true,createdAt:true},orderBy:{createdAt:"desc"}}))});
app.listen(PORT,()=>console.log("LeadFinder AI Enterprise backend online on "+PORT));
